### ISSUE TITLE
No indication that a config is malformed/incomplete

### ISSUE THREAD

**Issue by TicClick** [TicClick/steel#61]
for example, if a new field is missing, it'll just crash:

```
user@black-cube:~/stuff/steel$ cargo rw
   Compiling steel v0.7.2 (/home/user/stuff/steel)
--- snip ---
    Finished release [optimized] target(s) in 5.42s
     Running `target/x86_64-pc-windows-gnu/release/steel.exe`
user@black-cube:~/stuff/steel$ echo $?
101
```

# TODO

- [ ] load settings before everything else
- [ ] use them when setting logging level
- [ ] create application / mod plugin with settings
- [ ] return error from the setting loader/saver using `eyre`
  - [ ] on initialization failure, show a simple egui window
  - [ ] if the error happened during runtime, request the core to exit with error attached
  - [ ] in core, display the error in the same simple window

**Comment by TicClick** [comment]
note: lack of write access also goes here -- such as if a file or a directory are read-only
